### PR TITLE
Adds the usage of the header.author variable

### PR DESCRIPTION
**Pull request by niklas-heer**
This fixes issue #6 and contains the same code provided by Benny.
Because he is not familiar with how PRs work he asked me for help.

So here it is. 
Hopefully, this PR is acceptable. :)

### CODE REVIEW

**Comment by BennyBolivar** [comment]
I added support for the grav comment plugin too. Thanks for PR Niklas :)

**Comment by koca** [comment]
Hi niklas, 
thank you both @niklas-heer @BennyBolivar 👍 
:)

**Comment by koca** [comment]
and I guess benny figured out how PRs work :)

**Comment by BennyBolivar** [comment]
Finaly :D Thanks for merging :)

**Pull request closed without merging**
